# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reco.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'reco.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nreco.proto\x12\x0erecommendation\"3\n\rUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tnum_items\x18\x02 \x01(\x05\"5\n\x10NewsListResponse\x12\x10\n\x08news_ids\x18\x01 \x03(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2m\n\x10RecommendService\x12Y\n\x16GetNewsRecommendations\x12\x1d.recommendation.UserIdRequest\x1a .recommendation.NewsListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reco_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERIDREQUEST']._serialized_start=30
  _globals['_USERIDREQUEST']._serialized_end=81
  _globals['_NEWSLISTRESPONSE']._serialized_start=83
  _globals['_NEWSLISTRESPONSE']._serialized_end=136
  _globals['_RECOMMENDSERVICE']._serialized_start=138
  _globals['_RECOMMENDSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
