 # Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reco_pb2 as reco__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reco_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendServiceStub:
    """定义一个微服务（服务提供者）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNewsRecommendations = channel.unary_unary(
                '/recommendation.RecommendService/GetNewsRecommendations',
                request_serializer=reco__pb2.UserIdRequest.SerializeToString,
                response_deserializer=reco__pb2.NewsListResponse.FromString,
                _registered_method=True)


class RecommendServiceServicer:
    """定义一个微服务（服务提供者）
    """

    def GetNewsRecommendations(self, request, context):
        """定义一个叫 GetNewsRecommendations 的接口
        接收 UserIdRequest，返回 NewsListResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNewsRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNewsRecommendations,
                    request_deserializer=reco__pb2.UserIdRequest.FromString,
                    response_serializer=reco__pb2.NewsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.RecommendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.RecommendService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendService:
    """定义一个微服务（服务提供者）
    """

    @staticmethod
    def GetNewsRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendService/GetNewsRecommendations',
            reco__pb2.UserIdRequest.SerializeToString,
            reco__pb2.NewsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
